name: AWS Nitro enclave deployment
on: [push]
permissions:
  contents: write
  packages: write
  id-token: write
jobs: 
    build_enclave:
        name: build enclave
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Build EIF
              id: build-eif  
              uses: richardfan1126/nitro-enclaves-eif-build-action@v1.2.1
              with:
                docker-build-context-path: /
                # enable-ghcr-push: true
                # enable-artifact-sign: true
                eif-file-name: enclave.eif
                eif-info-file-name: enclave-info.json
                artifact-tag: ${{ github.sha }}
                # save-pcrs-in-annotation: true
                github-token: ${{ secrets.GITHUB_TOKEN }}