name: AWS Nitro enclave deployment
on: [push]
permissions:
  contents: write
  packages: write
  id-token: write
jobs: 
    build_enclave:
        name: build enclave
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Build EIF
              id: build-eif  
              uses: richardfan1126/nitro-enclaves-eif-build-action@v1.2.1
              with:
                docker-build-context-path: /
                eif-file-name: enclave.eif
                eif-info-file-name: enclave-info.json
                artifact-tag: ${{ github.sha }}
                github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload EIF and info file as artifacts
              uses: actions/upload-artifact@v4
              with:
                name: enclave-artifacts
                path: |
                  ${{ steps.build-eif.outputs.eif-file-path }}
                  ${{ steps.build-eif.outputs.eif-info-path }}
