name: Terraform Cleanup

on: [push]
permissions:
  contents: write
  packages: write
  id-token: write  
jobs:
  terraform-cleanup:
    name: "Post Apply Cleanup"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub repository"
        uses: actions/checkout@v2

      - name: Check for cleanup in commit message
        id: check_commit_message
        run: |
          if [[ "$(git log -1 --pretty=%B)" != *"cleanup"* ]]; then
            echo "Skipping job because the commit message does not contain 'cleanup'"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::717279690196:role/enclave
          aws-region: us-east-2

      - name: Terraform Init
        run: |
            cd terraform
            terraform init

      - name: Terraform Plan Destroy
        run: |
            cd terraform
            terraform plan -destroy -out=tfplan-destroy

      - name: "Terraform Apply Destroy"
        run: |
            cd terraform
            terraform apply -auto-approve tfplan-destroy
